Use db
AleksKurilo/WebLinkChecker pull request #1
Opened 2017-07-18 09:33 UTC by AleksKurilo

Chek hibernate validation

2017-07-18 09:40 UTC, AleksKurilo commented
Hi!

2017-07-18 09:47 UTC, gbtec-ext-dmytroshvechikov requested changes

2017-07-18 09:47 UTC, gbtec-ext-dmytroshvechikov commented on pom.xml
> +			<version>1.5.4.RELEASE</version>
версия не нужна

2017-07-18 09:47 UTC, gbtec-ext-dmytroshvechikov commented on pom.xml
> +			<version>5.1.34</version>
версия не нужна скорее всего (проверь)

2017-07-18 09:47 UTC, gbtec-ext-dmytroshvechikov commented on pom.xml
> +			<version>1.5.4.RELEASE</version>
версия не нужна

2017-07-18 09:47 UTC, gbtec-ext-dmytroshvechikov commented on pom.xml
> +			<version>1.5.4.RELEASE</version>
тебе вообще эта зависимость пока не нужна

2017-07-18 09:47 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/akproject/WebLinkChecker/WebLinkCheckerApplication.java
>  public class WebLinkCheckerApplication {
переименуй в ServiceApplication

2017-07-18 09:47 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/akproject/WebLinkChecker/model/User.java
> +    @Size(min = 3, max = 255)
убери это

2017-07-18 09:47 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/akproject/WebLinkChecker/model/UserRepository.java
> +public interface UserRepository extends CrudRepository<User, Long> {
вообще какие юзеры?! Что в тасках написано?

2017-07-18 09:53 UTC, AleksKurilo commented on pom.xml
> +			<version>5.1.34</version>
Проверил, нужна

2017-07-18 09:53 UTC, AleksKurilo commented on pom.xml
> +			<version>1.5.4.RELEASE</version>
убрал

2017-07-18 09:53 UTC, AleksKurilo commented on src/main/java/com/akproject/WebLinkChecker/WebLinkCheckerApplication.java
>  public class WebLinkCheckerApplication {
Переименовал

2017-07-20 12:13 UTC, gbtec-ext-dmytroshvechikov requested changes

2017-07-20 12:13 UTC, gbtec-ext-dmytroshvechikov commented on pom.xml
> +		<!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-data-jpa -->
убери комменты, они тут бесполезны

2017-07-20 12:13 UTC, gbtec-ext-dmytroshvechikov commented on pom.xml
> +		<!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-test -->
убери комменты, они тут бесполезны

2017-07-20 12:13 UTC, gbtec-ext-dmytroshvechikov commented on pom.xml
>  		<dependency>
это зависимость не нужна по идее, её тянет starter-web. Проверь

2017-07-20 12:13 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/akproject/WebLinkChecker/ServiceApplication.java
> +
убери пустые строчки

2017-07-20 12:13 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/akproject/WebLinkChecker/model/Project.java
>  @Table(name = "users")
почему проект хранится в таблице users?)) Как по мне @Table тут вообще не нужно

2017-07-20 12:13 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/akproject/WebLinkChecker/model/Project.java
>      //default constructor
убери комментарии, незачем писать на столе, что это стол - это и так всем понятно))

2017-07-20 12:13 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/akproject/WebLinkChecker/model/ProjectRepository.java
> +
пустые строчки

2017-07-20 12:13 UTC, gbtec-ext-dmytroshvechikov commented on src/main/resources/application.yml
> +       hbm2ddl_auto: create-drop
spring:
  jpa:
    hibernate:
      ddl-auto: update - должно быть вот так, даже идея подсвечивает. Не уверен, что твоё работает

2017-07-21 10:36 UTC, AleksKurilo commented on pom.xml
> +		<!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-data-jpa -->
Сделано

2017-07-21 10:36 UTC, AleksKurilo commented on pom.xml
> +		<!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-test -->
Сделано

2017-07-21 10:37 UTC, AleksKurilo commented on pom.xml
>  		<dependency>
Да действительно

2017-07-21 10:40 UTC, AleksKurilo commented on src/main/java/com/akproject/WebLinkChecker/ServiceApplication.java
> +
Убрал

2017-07-21 10:44 UTC, AleksKurilo commented on src/main/java/com/akproject/WebLinkChecker/model/Project.java
>  @Table(name = "users")
Если ты не против, я пока оставлю @table, но укажу таблицу "project", мне для себя пометка если будут еще таблицы, чтоб в них не путаться.

2017-07-21 10:46 UTC, AleksKurilo commented on src/main/java/com/akproject/WebLinkChecker/model/Project.java
>      //default constructor
Ок, убрал ! ))

2017-07-21 10:47 UTC, AleksKurilo commented on src/main/java/com/akproject/WebLinkChecker/model/ProjectRepository.java
> +
Стерты с лица Земли !

2017-07-21 10:51 UTC, AleksKurilo commented on src/main/resources/application.yml
> +       hbm2ddl_auto: create-drop
Привел в порядок )

2017-07-21 11:21 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/akproject/WebLinkChecker/model/Project.java
> +@Table(name = "project")
та убери ты этот @Table - хибернейт сам тебе сгенерит имя таблицы

2017-07-21 11:22 UTC, gbtec-ext-dmytroshvechikov commented on src/main/resources/application.yml
> +       hbm2ddl_auto: update
я ж тебе скинул пример!
spring:
  jpa:
    hibernate:
      ddl-auto: update

2017-07-21 11:54 UTC, AleksKurilo commented on src/main/java/com/akproject/WebLinkChecker/model/Project.java
> +@Table(name = "project")
Убрал

2017-07-21 11:57 UTC, AleksKurilo commented on src/main/resources/application.yml
> +       hbm2ddl_auto: update
Прости просмотрел ((
Поправил как надо!

2017-07-24 05:22 UTC, merged