Added-data-validation
AleksKurilo/WebLinkChecker pull request #5
Opened 2017-08-08 12:44 UTC by AleksKurilo

2017-08-14 07:40 UTC, gbtec-ext-dmytroshvechikov requested changes

2017-08-14 07:40 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/controllers/ProjectBinding.java
> +
добавь приватный конструктор через ломбок и final к классу

2017-08-14 07:40 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +    private BindingResult bindingResult;
фуфу, оно не нужно тут

2017-08-14 07:40 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +        this.bindingResult = bindingResult;
зачем его тут инициализировать? Его и так можно использовать

2017-08-14 07:40 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +            return "redirect:"+BASE_PATH+SAVE_ERROR;
плохой план, отдавай ту же вьюху и в ней показывай ошибки

2017-08-14 07:40 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +        return "redirect:"+BASE_PATH+"/";
/ в конце не нужен по идее, надо в IDE сочетание клавиш для автоформата - оно умеет красиво форматировать код

2017-08-14 07:40 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +    public ModelAndView saveViewError(){
не нужен этот метод

2017-08-14 07:40 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +        this.bindingResult = bindingResult;
тоже самое, что и в инсерте

2017-08-14 07:40 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +        return "redirect:"+BASE_PATH+"/";
убери этот /, либо внеси его в BASE_PATH

2017-08-14 07:40 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/model/Project.java
> +    @Size(min = 3, max = 255, message = "Size must be between 3 and 255 !")
плохой план писать тут сообщения, погляди как локализировать сообщения в спринге. Ключевые слова spring i18n и message properties

2017-08-14 07:40 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +       // Project exproject = projectRepository.findOne(id);
это не то. Создать отдельные классы ProjectInsert, ProjectUpdate, которые будут содержать инфу из форм и передавай их сюда. В случае обновления сначала достаешь по id проект, а потом обновляешь поля, доставая их из ProjectUpdate объекта

2017-08-14 07:56 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/controllers/ProjectBinding.java
> +
Сделано

2017-08-14 08:32 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +        return "redirect:"+BASE_PATH+"/";
добавил в BASE_PATH

2017-08-18 14:06 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +    private BindingResult bindingResult;
убрал

2017-08-18 14:07 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +        this.bindingResult = bindingResult;
убрал

2017-08-18 14:08 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +            return "redirect:"+BASE_PATH+SAVE_ERROR;
ок, подправил

2017-08-18 14:08 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +        return "redirect:"+BASE_PATH+"/";
Сделал красиво! )

2017-08-18 14:08 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +    public ModelAndView saveViewError(){
Убрал

2017-08-18 14:09 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +        this.bindingResult = bindingResult;
ок

2017-08-21 06:49 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/model/Project.java
> +    @Size(min = 3, max = 255, message = "Size must be between 3 and 255 !")
Сделал отдельный файл файл с сообщениями при помощи MessageSource

2017-08-22 05:57 UTC, gbtec-ext-dmytroshvechikov requested changes

2017-08-22 05:57 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/config/WebLinkCheckerConfig.java
> +    public MessageSource messageSource(){
спринг бут умеет сам это конфигурить насколько я помню

2017-08-22 05:57 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +public final class ProjectController {
final нужен на классах, от которых мы точно не будем наследоваться. Насчет контроллера это сложный вопрос. Думаю здесь оно не надо. Я говорил добавить на класс с константами, который наследовать или создавать инстанс вообще нет смысла

2017-08-22 05:57 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +            redirectAttr.addFlashAttribute(BindingResult.MODEL_KEY_PREFIX + "project", bindingResult);
форматирование

2017-08-22 05:57 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +        projectService.save(projectInsert);
думаю есть смысл сделать метод insert в сервисе отдельно, а так все ок

2017-08-22 05:57 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/controllers/ProjectInsert.java
> +    String name;
почему не private?

2017-08-22 05:57 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +        Project project = new Project(projectInsertName);
та убери ты эти констукторы, используй сеттеры. project.setName(insert.getName());

2017-08-22 05:57 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +        Project project = new Project(projectInsertName);
просто в проекте когда станет больше полей конструктор будет выглядеть громоздко

2017-08-22 07:39 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/config/WebLinkCheckerConfig.java
> +    public MessageSource messageSource(){
Без него не работает, выводит default message

2017-08-22 07:40 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +public final class ProjectController {
Ок, понял

2017-08-22 07:45 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +            redirectAttr.addFlashAttribute(BindingResult.MODEL_KEY_PREFIX + "project", bindingResult);
Уже заучил CTRL + ALT + L

2017-08-23 04:33 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +        Project project = new Project(projectInsertName);
Ок

2017-08-23 04:57 UTC, gbtec-ext-dmytroshvechikov requested changes

2017-08-23 04:57 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/config/WebLinkCheckerConfig.java
> +    public MessageSource messageSource(){
это конфигурится через application.yml, ищи там basename

2017-08-23 04:57 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +public final class ProjectController {
убери final

2017-08-23 04:57 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
зачем access=PRIVATE?

2017-08-23 04:57 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +    @RequestMapping(path = "/", method = RequestMethod.GET)
путь можно вообще убрать, если он совпадает с BASE_PATH

2017-08-23 04:57 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +    public String save(@ModelAttribute("project") @Valid ProjectInsert projectInsert, BindingResult bindingResult, RedirectAttributes redirectAttr) {
переименуй в insert

2017-08-23 04:57 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +            return "redirect:" + ProjectBinding.BASE_PATH + ProjectBinding.SAVE;
сделай статический импорты для констант - так будет получше выглядеть мне кажется

2017-08-23 04:57 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +    public String update(@PathVariable long id, @ModelAttribute("project") @Valid ProjectUpdate projectUpdate, BindingResult bindingResult, RedirectAttributes redirectAttributes) {
сделай Long вместо long

2017-08-23 04:57 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +    public ProjectRepository projectRepository;
добавь final

2017-08-23 04:57 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +    public void save(ProjectInsert projectInsert) {
переименуй в insert

2017-08-23 04:57 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +        Project project = new Project();
нет, здесь ты из репозитория вытаскиваешь по id проект, обновляешь поля и потом уже сохраняешь

2017-08-23 04:57 UTC, gbtec-ext-dmytroshvechikov commented on src/main/resources/templates/update.ftl
> +    <form method="post" action="">
почему action пустой?

2017-08-23 04:57 UTC, gbtec-ext-dmytroshvechikov commented on src/main/resources/templates/update.ftl
> +    <form method="post" action="">
у тебя ж обновление не работает по сути

2017-08-23 04:57 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +        Project project = new Project();
добавь apache commons-lang3 и юзай Validate в каждом методе, где есть параметры. Примерно вот так Validate.notNull(projectUpdate, "projectUpdate"); Оно кажется что проверять каждый чих не надо (сам такой еще недавно был), но реально удобно когда что-то идет не так оно не проходит на уровень ниже и не надо даже зачастую дебажить, чтоб понять где и что пошло не так

2017-08-23 05:57 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +public final class ProjectController {
убрал

2017-08-23 05:58 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +    @RequestMapping(path = "/", method = RequestMethod.GET)
Отлично, убрал

2017-08-23 06:01 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +    public String save(@ModelAttribute("project") @Valid ProjectInsert projectInsert, BindingResult bindingResult, RedirectAttributes redirectAttr) {
Переименовал

2017-08-23 06:03 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +            return "redirect:" + ProjectBinding.BASE_PATH + ProjectBinding.SAVE;
Ok

2017-08-23 06:07 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +    public String update(@PathVariable long id, @ModelAttribute("project") @Valid ProjectUpdate projectUpdate, BindingResult bindingResult, RedirectAttributes redirectAttributes) {
Заменил

2017-08-23 06:08 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +    public ProjectRepository projectRepository;
добавил

2017-08-23 06:13 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +    public void save(ProjectInsert projectInsert) {
Переименовал

2017-08-23 06:35 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +        Project project = new Project();
Сделал

а, Validate из apache commons-lang3 интересная штука, но не будет ли она захламлять код?

2017-08-25 04:39 UTC, merged