Clean code
AleksKurilo/WebLinkChecker pull request #9
Opened 2017-08-25 10:09 UTC by AleksKurilo

2017-08-30 05:54 UTC, gbtec-ext-dmytroshvechikov requested changes

2017-08-30 05:54 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/config/ConversionConfiguration.java
> +public class ConversionConfiguration {
оно не надо, уже есть несколько сконфигуренных сервисов, например, mvcConversionService

2017-08-30 05:54 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/model/Project.java
> +    private String uuid = UUID.randomUUID().toString();
не, давай это перенесем в сервис в insert

2017-08-30 05:54 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/model/ProjectProjection.java
> +    @NotNull
ты ж проекцию нигде не валидируешь - смысла в аннотации нет

2017-08-30 05:54 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectFacade.java
> +        while(iteratorProject.hasNext()) {
в целом все правильно, но погляди как это сделать через стримы - это более актуально и лаконично

2017-08-30 05:54 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectFacade.java
> +    private ConversionService conversionService;
final

2017-08-30 05:54 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectFacade.java
> +@Data
это тут не надо

2017-08-30 05:54 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectFacade.java
> +        List<ProjectProjection> projectProjections = new ArrayList<ProjectProjection>();
кстати если уж ты делаешь так, то есть смысл создавать arraylist c заданным размером, т. к. ты его знаешь наверняка new ArrayList<>(projects.size()), но лучше разберись как сделать через стримы

2017-08-30 05:54 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectFacade.java
> +        projectService.insert(projectInsert);
валидируй входящие параметры во всех методах

2017-08-30 05:54 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +        Validate.notNull(projectInsert, "projectInsert is null in ProjectService.class");
нет смысла писать длинную писанину. Он кажется внутри генерит уже сообщение. Посмотри в исходники. Возможно 2й параметр не нужен или просто нужно задать имя валидируемого объекта Validate.notNull(projectInsert, "projectInsert")

2017-08-30 05:54 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +        Validate.notNull(projectUpdate, "projectUpdate is null in ProjectService.class");
проверяй что uuid не пустой

2017-08-30 05:54 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +        Validate.notNull(project, "project is null in ProjectService.class");
тут особо не смысла доставать проект, просто напиши в репозитории метод удаления по uuid

2017-08-30 05:54 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +        Project project = projectRepository.findByUuid(uuid);
валидируй, что uuid не пустой

2017-08-30 05:54 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectToProjectProjection.java
> +public final class ProjectToProjectProjection implements Converter<Project, ProjectProjection> {
переименуй ProjectToProjectProjection в ProjectToProjectProjectionConverter

2017-08-30 05:54 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectToProjectProjection.java
> +        ProjectProjection projectProjection = new ProjectProjection();
валидируй входящие параметры

2017-08-30 06:44 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/model/ProjectProjection.java
> +    @NotNull
Согласен

2017-08-30 06:49 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/service/ProjectFacade.java
> +    private ConversionService conversionService;
Ок

2017-08-30 06:52 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/service/ProjectFacade.java
> +        projectService.insert(projectInsert);
Ок, сделал

2017-08-30 06:54 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +        Validate.notNull(projectUpdate, "projectUpdate is null in ProjectService.class");
Ок, добавил

2017-08-30 06:58 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/service/ProjectToProjectProjection.java
> +public final class ProjectToProjectProjection implements Converter<Project, ProjectProjection> {
Сделал

2017-08-30 07:01 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/service/ProjectToProjectProjection.java
> +        ProjectProjection projectProjection = new ProjectProjection();
Сделал

2017-08-31 04:43 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/model/Project.java
> +    private String uuid = UUID.randomUUID().toString();
Легко! Перенес

2017-08-31 04:47 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/service/ProjectFacade.java
> +@Data
Заменил на @RequiredArgsConstructor (конструктор с 1 параметром для каждого поля), что бы "билось" c final в "private final ConversionService conversionService;"

2017-08-31 06:14 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/service/ProjectFacade.java
> +        while(iteratorProject.hasNext()) {
Сделал, кстати спасибо! Там действительно много чего интересного!

2017-08-31 06:14 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/service/ProjectFacade.java
> +        List<ProjectProjection> projectProjections = new ArrayList<ProjectProjection>();
ок

2017-08-31 07:43 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +        Project project = projectRepository.findByUuid(uuid);
Ок, добавил

2017-08-31 09:19 UTC, gbtec-ext-dmytroshvechikov requested changes

2017-08-31 09:19 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +    private ProjectFacade projectFacade;
final

2017-08-31 09:19 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/model/Project.java
> +    private String uuid;
добавь индекс по этому полю

2017-08-31 09:19 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/model/ProjectProjection.java
> +
форматирование

2017-08-31 09:19 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/repository/ProjectRepository.java
>      List<Project> findByName(String name);
это метод используется? Есть да, то добавь индекс в сущность

2017-08-31 09:19 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/repository/ProjectRepository.java
> +    Project findByUuid(String uuid);
переименуй в findOneByUuid

2017-08-31 09:19 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectFacade.java
> +        Validate.notNull(projectInsert, "projectInsert is null in ProjectFacade.class");
давай добавлять строку между Validate'ами и остальным кодом, чтоб визуально разделять

2017-08-31 09:19 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +        Validate.notNull(projects, "List<Project> projects is null in ProjectService.class");
тут всегда будет not null, не смысла в этой проверке

2017-08-31 09:19 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +        Validate.notNull(uuid, "uuid is null in ProjectService.class");
измени на notBlank

2017-08-31 09:19 UTC, gbtec-ext-dmytroshvechikov commented on src/main/resources/templates/projects.ftl
> +            <th>UUID</th>
думаю для обычного юзера эта графа вообще ни о чем не говорит, ее можно убрать и ты проверил, что после добавления uuid работают формы добавления/редактирования?

2017-08-31 10:28 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/config/ConversionConfiguration.java
> +public class ConversionConfiguration {
Ок

2017-08-31 10:37 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +        Validate.notNull(project, "project is null in ProjectService.class");
Согласен

2017-08-31 10:39 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
> +    private ProjectFacade projectFacade;
сделал

2017-08-31 10:41 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/model/ProjectProjection.java
> +
Сделал

2017-08-31 10:43 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/repository/ProjectRepository.java
> +    Project findByUuid(String uuid);
Ок

2017-08-31 10:44 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +        Validate.notNull(projects, "List<Project> projects is null in ProjectService.class");
Ок, убрал.

2017-08-31 10:51 UTC, AleksKurilo commented on src/main/resources/templates/projects.ftl
> +            <th>UUID</th>
Графу убрал. Формы проверял, работают хотя там идет связь с project, а не c projectInsert и projectUpdate. Есть ли смыл привязать формы к новым объектам projectInsert /projectUpdate?

2017-08-31 10:51 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +        Validate.notNull(uuid, "uuid is null in ProjectService.class");
Изменил

2017-08-31 10:52 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/repository/ProjectRepository.java
>      List<Project> findByName(String name);
Нет метод не использовался, в связи с этим я его убрал

2017-09-01 07:19 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/model/Project.java
> +    private String uuid;
Добавил, c gjvjom. hibernate-search-orm версии 5.5.2.Final

2017-09-01 07:27 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/service/ProjectFacade.java
> +        Validate.notNull(projectInsert, "projectInsert is null in ProjectFacade.class");
Добавил, и сократил сообщение

2017-09-11 05:09 UTC, gbtec-ext-dmytroshvechikov requested changes

2017-09-11 05:09 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
>      @RequestMapping( method = RequestMethod.GET)
что за отступ с одной стороны?)

2017-09-11 05:09 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/model/Project.java
> +                @Index(columnList = "uuid", name = "uuid")
он еще и уникальный должен быть

2017-09-11 05:09 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/model/Project.java
> +    @NotNull
замени на @NotEmpty

2017-09-11 05:09 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectFacade.java
> +        Validate.notNull(projectInsert, "projectInsert is null in ProjectFacade.class");
сделай свой класс для валидации, который будет принимать объект для валидации и его имя, а внутри будешь вызывать тот же Validate и формировать дефолтное сообщение, например, "Object '%objectName%' cannot be null"

2017-09-11 05:09 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectFacade.java
> +        Validate.notNull(projectUpdate, "projectUpdate is null in ProjectFacade.class");
валидируй что uuid не пустой

2017-09-11 05:09 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectFacade.java
> +        Validate.notNull(uuid, "uuid is null in ProjectService.class");
замени на notBlank

2017-09-11 05:09 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +        return projects;
сделай в одну строчку

2017-09-11 05:10 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/controllers/ProjectController.java
>      @RequestMapping( method = RequestMethod.GET)
Есть, поправил

2017-09-11 05:21 UTC, AleksKurilo commented on src/main/java/com/web/link/checker/project/model/Project.java
> +                @Index(columnList = "uuid", name = "uuid")
Сделал

2017-09-12 07:49 UTC, gbtec-ext-dmytroshvechikov requested changes

2017-09-12 07:49 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +        ValidateService.validateNotBlank(uuid, "in delete method");
1) Назови это ValidateUtils
2) второй раз validate вообще нет никакого смысла писать - просто notBlank вполне сойдёт. 
3) А параметр тогда уж должен называться uuid, чтоб в итоге получилось сообщение вроде "'uuid' cannot be null"

2017-09-12 07:49 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ValidateService.java
> +public class ValidateService {
1) final и приватный дефолтный конструктор добавь
2) переименуй методы, как я писал выше
3) Оберни %s в ''
4) Перенеси класс в пакет utils

2017-09-12 08:28 UTC, gbtec-ext-dmytroshvechikov requested changes

2017-09-12 08:28 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectFacade.java
> +@Service
Фасад все таки не сервис, сервис у нас это слой ниже. Поменяй просто на компонент

2017-09-12 08:28 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectFacade.java
> +        Validate.notNull(projectInsert, "projectInsert is null in ProjectFacade.class");
у тебя ж теперь есть сообщение нормальное внутри, поменяй это на имя объекта

2017-09-12 08:28 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectFacade.java
> +        Validate.notNull(projectUpdate, "projectUpdate is null in ProjectFacade.class");
и здес тоже сообщение поменяй

2017-09-12 08:28 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectFacade.java
> +        Validate.notNull(uuid, "uuid is null in ProjectService.class");
замени на notBlank и сообщение

2017-09-12 08:28 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectService.java
> +       ValidateUtils.notBlank(uuid, "uuid");
форматирование

2017-09-12 08:28 UTC, gbtec-ext-dmytroshvechikov commented on src/main/java/com/web/link/checker/project/service/ProjectToProjectProjectionConverter.java
> +        Validate.notNull(project, "project is null in ProjectToProjectProjectionConverter.class");
сообщение

2017-09-13 05:05 UTC, merged